[package]
name = "ttr-protocol"
version = "0.1.0"
authors = ["Sean Purcell <me@seanp.xyz>"]
edition = "2018"

[build-dependencies]
protoc-rust = "2.14"

[dependencies]
derive_more = "0.99"
protobuf = "2.14"
thiserror = "1.0"

[dev-dependencies]
hex = "0.4"
